print("Создаем список")
a = (int(input("Первое число: ")))
b = (int(input("Второе число: ")))
c = (int(input("Третье число: ")))
d = (int(input("Четвертое число: ")))
e = (int(input("Пятое число: ")))
f=(a,b, c, d, e)
print=(len(f))
